variable "project_id" {}
variable "master_machine_type" {}
variable "master_image" {}
variable "vpc_network" {}
variable "worker_machine_type" {}
variable "worker_image" {}
variable "instance_group_name" {}
variable "base_instance_name" {}
variable "zone" {}
variable "cluster_size" {}
